# For the standard ErgoDox Wireless dongle setup with the latest Raytac "green"
# dongle, you do not need to modify this file. If you are using a different
# dongle such as the older Raytac "blue" dongle, you will need to modify
# "board". For a dongleless setup, you will need to modify both "board" and
# "shield". Please see "readme.md" for more details.
include:
  - board: seeeduino_xiao_ble
    shield: slicemk_ergodox_dongle dongle_screen
    artifact-name: dongle-screen

  - board: slicemk_ergodox_202108_green_left
    shield: slicemk_ergodox_leftsingle
    artifact-name: left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n


  - board: slicemk_ergodox_202108_green_right
    shield: slicemk_ergodox_rightsingle
    artifact-name: right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: screen-reset
